(function(){'use strict';
var INDEX='portfolio/categories.json', VALID=['active','beta','coming-soon'], ID=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
function fetchJson(url){return fetch(url,{headers:{Accept:'application/json'}}).then(function(r){if(!r.ok)throw new Error(url+' 요청 실패 ('+r.status+')');return r.json().catch(function(){throw new Error(url+' JSON 형식 오류');});});}
function text(v,f){return typeof v==='string'&&v.trim()?v.trim():(f||'');}
function arr(v){return Array.isArray(v)?v.filter(function(x){return typeof x==='string'&&x.trim();}).map(function(x){return x.trim();}):[];}
function url(v,issues,ctx){var raw=text(v,'');if(!raw)return'';try{var u=new URL(raw,document.baseURI);if(u.protocol!=='http:'&&u.protocol!=='https:'){issues.push(ctx+': URL protocol');return'';}return u.href;}catch(e){issues.push(ctx+': URL format');return'';}}
function item(raw,cat,i,seen,issues){var c=cat.key+'['+i+']';if(!raw||typeof raw!=='object'||Array.isArray(raw))return null;var id=text(raw.id,''),name=text(raw.name,''),short=text(raw.shortDescription,'');if(!ID.test(id)||!name||!short||seen.has(id)){issues.push(c+': invalid/duplicate item');return null;}seen.add(id);var status=VALID.indexOf(raw.status)>=0?raw.status:'active';return{id:id,name:name,shortDescription:short,fullDescription:text(raw.fullDescription,short),icon:text(raw.icon,'fas fa-cube'),tags:arr(raw.tags),status:status,version:text(raw.version,''),updatedAt:text(raw.updatedAt,''),featured:raw.featured===true,repoUrl:url(raw.repoUrl,issues,c),liveUrl:url(raw.liveUrl,issues,c),actionLabel:text(raw.actionLabel,'열기'),features:arr(raw.features),categoryKey:cat.key,categoryLabel:cat.label};}
function normalizeCategories(p){if(!p||!Array.isArray(p.categories))throw new Error('categories 배열이 없습니다.');var seen=new Set();return p.categories.map(function(r,i){var key=text(r&&r.key,''),source=text(r&&r.source,'');if(!ID.test(key)||!source||seen.has(key))throw new Error('categories['+i+'] 오류');seen.add(key);return{key:key,label:text(r.label,key),description:text(r.description,''),source:source};});}
function loadCategory(cat){var issues=[];return fetchJson(cat.source).then(function(p){var raw=Array.isArray(p)?p:(p&&p.items);if(!Array.isArray(raw))throw new Error(cat.key+' items 배열 없음');var seen=new Set();return{key:cat.key,label:cat.label,description:cat.description,items:raw.map(function(x,i){return item(x,cat,i,seen,issues);}).filter(Boolean),issues:issues,error:''};}).catch(function(e){return{key:cat.key,label:cat.label,description:cat.description,items:[],issues:issues,error:e.message};});}
function load(){return fetchJson(INDEX).then(normalizeCategories).then(function(cats){return Promise.all(cats.map(loadCategory));});}
window.PortfolioCatalog={load:load};})();